version: '2'

services:
  config-server:
    image: springcommunity/spring-petclinic-config-server
    container_name: config-server
    mem_limit: 512M
    ports:
     - 8888:8888

  discovery-server:
    image: springcommunity/spring-petclinic-discovery-server
    container_name: discovery-server
    mem_limit: 512M
    depends_on:
      - config-server
    entrypoint: ["./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8761:8761

  customers-service:
    image: springcommunity/spring-petclinic-customers-service
    container_name: customers-service
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "${COV_AGENT_ARGS},port=8051", "org.springframework.boot.loader.JarLauncher"]
    ports:
    - 8081:8081
    - 8051:8051
    volumes:
      - type: bind
        source: '/var/lib/jenkins/workspace/Testing Jobs/PetClinic-Jenkins (main branch)/petclinic/spring-petclinic-customers-service/src/test/resources/coverage'
        target: /tmp/coverage
  visits-service:
    image: springcommunity/spring-petclinic-visits-service
    container_name: visits-service
    user: 0:0
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
#    env_file:
#      - /home/ec2-user/microservices/spring-petclinic-microservices/spring-petclinic-visits-service/src/test/resources/coverage/cov.env
#    environment:
#      JAVA_OPTS: '-javaagent:/tmp/coverage/agent.jar=settings=/tmp/coverage/agent.properties,runtimeData=/tmp/coverage/runtime_coverage'
    ports:
     - 8882:8082
     - 8052:8052 # cov agent
    volumes:
      - type: bind
        source: '/var/lib/jenkins/workspace/Testing Jobs/PetClinic-Jenkins (main branch)/petclinic/spring-petclinic-visits-service/src/test/resources/coverage'
        target: /tmp/coverage
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
  vets-service:
    user: root:root
    image: springcommunity/spring-petclinic-vets-service
    container_name: vets-service
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "${COV_AGENT_ARGS},port=8053", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8083:8083
     - 8053:8053 # cov agent
    volumes:
      - type: bind
        source: '/var/lib/jenkins/workspace/Testing Jobs/PetClinic-Jenkins (main branch)/petclinic/spring-petclinic-vets-service/src/test/resources/coverage'
        target: /tmp/coverage

  api-gateway:
    image: springcommunity/spring-petclinic-api-gateway
    container_name: api-gateway
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8099:8080

  tracing-server:
    image: openzipkin/zipkin
    container_name: tracing-server
    mem_limit: 512M
    environment:
    - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
    ports:
     - 9411:9411

  admin-server:
    image: springcommunity/spring-petclinic-admin-server
    container_name: admin-server
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 9090:9090

# Commment out to save space
  ## Grafana / Prometheus
#
#  grafana-server:
#    build: ./docker/grafana
#    container_name: grafana-server
#    mem_limit: 256M
#    ports:
#    - 3000:3000
#
#  prometheus-server:
#    build: ./docker/prometheus
#    container_name: prometheus-server
#    mem_limit: 256M
#    ports:
#    - 9091:9090
#